# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: uaf-jupyterhub-asf@alaska.edu
author_name: OSL Admin
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: server
labextension_name: oslnotify
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: oslnotify
repository: ''
test: false
viewer_name: ''

