# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: uaf-jupyterhub-asf@alaska.edu
author_name: OpenScienceLab Admin
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: opensarlab_controlbtn
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: opensarlab_controlbtn
repository: https://github.com/ASFOpenSARlab/opensarlab-extensions/blob/main/README.md
test: false
viewer_name: ''

