---
  name: "Step 2: Publish Release"
  on:  # yamllint disable-line rule:truthy
    workflow_dispatch:
      inputs:
        environment:
          description: "GitHub environment to use for secrets and variables"
          default: "test"
          required: true
        tag:
          description: "Tag of release to publish"
          required: true
        branch:
          description: "The target branch"
          required: false
        release_url:
          description: "The URL of the draft GitHub release"
          required: false
        # steps_to_skip:
        #   description: "Comma separated list of steps to skip"
        #   required: false
  
  jobs:
    publish_release:
      runs-on: ubuntu-latest
      environment: ${{ github.event.inputs.environment }}
      permissions:
        # This is useful if you want to use PyPI trusted publisher
        # and NPM provenance
        id-token: write
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
  
        # - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
  
        # - name: Populate Release
        #   id: populate-release
        #   uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@v2
        #   with:
        #     token: ${{ secrets.PUBLISH_GITHUB_PAT }}
        #     branch: ${{ github.event.inputs.branch }}
        #     release_url: ${{ github.event.inputs.release_url }}
        #     steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

        - uses: robinraju/release-downloader@v1
          with:
            tag: ${{ github.event.inputs.tag }}
            out-file-path: dist
  
        # - name: Finalize Release
        #   id: finalize-release
        #   # env:
        #     # The following are needed if you use legacy PyPI set up
        #     # PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        #     # PYPI_TOKEN_MAP: ${{ secrets.PYPI_TOKEN_MAP }}
        #     # TWINE_USERNAME: __token__
        #     # The folliwing is needed to publish to NPM
        #     # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        #   uses: jupyter-server/jupyter-releaser/.github/actions/finalize-release@v2
        #   with:
        #     token: ${{ secrets.PUBLISH_GITHUB_PAT }}
        #     release_url: ${{ steps.populate-release.outputs.release_url }}
          
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_TOKEN }}
            repository-url: ${{ vars.REPOSITORY_URL }}
    
        - name: "** Next Step **"
          if: ${{ success() }}
          run: |
            echo "Verify the final release"
            echo ${{ steps.finalize-release.outputs.release_url }}
  
        - name: "** Failure Message **"
          if: ${{ failure() }}
          run: |-
            echo "Failed to Publish the Draft Release Url:"
            echo ${{ steps.populate-release.outputs.release_url }}