name: "Build and Publish Frontend To PyPI"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment to use for secrets and variables"
        default: "test"
        required: true
      version:
        description: "Version of the package"
        required: true


jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: ${{ github.event.inputs.environment }}
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install build twine hatch jupyterlab

      - name: Setup
        run: |
          echo "Updating Version"
          hatch version ${{ github.event.inputs.version }}

      - name: Build
        run: |
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
