name: "Publish Frontend To PyPI"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment to use for secrets and variables"
        default: "test"
        required: true
  workflow_call:
    inputs:
      environment:
        description: "GitHub environment to use for secrets and variables"
        type: string
        default: "test"
        required: true

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: ${{ github.event.inputs.environment }}
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1


# jobs:
#   publish_release:
#     runs-on: ubuntu-latest
#     environment: ${{ github.event.inputs.environment }}
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Upload Python
#         run: |
#           python3 -m pip install --upgrade build
#           python3 -m build
          
#       - name: Upload Distribution Archives
#         run: |
#           python3 -m pip install --upgrade twine
          
#           if [${{ github.event.inputs.environment == 'prod' }}]; then
#             echo "TWINE_REPOSITORY_URL=https://pypi.org/legacy/" >> $GITHUB_ENV
#           else
#             echo "TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/" >> $GITHUB_ENV
#           fi
#           python3 -m twine upload --repository testpypi dist/*

